# Generated by Django 4.0.4 on 2022-05-15 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('last_modified_date', models.BigIntegerField(verbose_name='Last modified date')),
                ('is_editable', models.BooleanField(verbose_name='Is editable')),
                ('is_private', models.BooleanField(verbose_name='Is private')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_creator', to='main.user')),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_modified_user', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_group', to='main.group')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('request_date', models.BigIntegerField(verbose_name='Request date')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author', to='main.user')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_group', to='main.group')),
                ('incoming_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_incoming_user', to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('event_date', models.BigIntegerField(verbose_name='Event date')),
                ('last_modified_date', models.BigIntegerField(verbose_name='Last modified date')),
                ('is_editable', models.BooleanField(verbose_name='Is editable')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_author', to='main.user')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_group', to='main.group')),
                ('last_modified_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_last_modified_user', to='main.user')),
            ],
        ),
    ]
