# Generated by Django 4.0.4 on 2022-05-15 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_group_usergrouprelation_request_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='last_modified_user_id',
            new_name='last_modified_user',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='last_modified_user_id',
            new_name='last_modified_user',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='incoming_user_id',
            new_name='incoming_user',
        ),
        migrations.RenameField(
            model_name='usergrouprelation',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='usergrouprelation',
            old_name='user_id',
            new_name='user',
        ),
    ]
